# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json

matches:
  - trigger: ":i"
    replace: "Issue"

  - trigger: ";i"
    replace: "Issue "

  - trigger: ";qme"
    replace: "What questions do you have for me?"

  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
