#!/usr/bin/env zsh

# NOTE probably don't use this. Instead if using zsh use "typeset -U path"

# Remove duplicate entries from PATH

typeset -a paths result
paths=($path)

while [[ ${#paths} -gt 0 ]]; do
  p="${paths[1]}"
  shift paths
  [[ -z ${paths[(r)$p]} ]] && result+="$p"
done

echo ${(j+:+)result}
